# Generated by Django 5.0.3 on 2024-04-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
