# Generated by Django 5.0.3 on 2024-04-14 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='transimission',
            new_name='transmission',
        ),
    ]
